
CREATE TABLE tpcds.call_center (
    cc_call_center_sk INT NOT NULL, 
    cc_call_center_id STRING NOT NULL, 
    cc_rec_start_date DATE, 
    cc_rec_end_date DATE, 
    cc_closed_date_sk INT, 
    cc_open_date_sk INT, 
    cc_name STRING, 
    cc_class STRING, 
    cc_employees INT, 
    cc_sq_ft INT, 
    cc_hours STRING, 
    cc_manager STRING, 
    cc_mkt_id INT, 
    cc_mkt_class STRING, 
    cc_mkt_desc STRING, 
    cc_market_manager STRING, 
    cc_division INT, 
    cc_division_name STRING, 
    cc_company INT, 
    cc_company_name STRING, 
    cc_street_number STRING, 
    cc_street_name STRING, 
    cc_street_type STRING, 
    cc_suite_number STRING, 
    cc_city STRING, 
    cc_county STRING, 
    cc_state STRING, 
    cc_zip STRING, 
    cc_country STRING, 
    cc_gmt_offset DECIMAL(5, 2), 
    cc_tax_percentage DECIMAL(5, 2)
)
USING DELTA
TBLPROPERTIES ('primaryKey' = 'cc_call_center_sk');
